### ISSUE TITLE
can't install client (or presumably server) from requirements.txt

### ISSUE THREAD

**Issue by jackkordas** [globus/globus-cwlogger#33]
I'm not terrible familiar with this, but I think the need for #subdirectory=client is getting in the way.  When I clone the repo, remove the server stuff and moved the client stuff into the root the following line works in requirements.txt

-e git+https://github.com/jackkordas/globus-cwlogger#egg=globus_cw_client

**Comment by sirosen** [comment]
I only recently spotted this issue -- slipped through my email somehow.

There are a bunch of ways this can fail because pip has so many different behaviors, so I'm not sure which flavor of failure you were seeing. I don't actually see errors putting the requirement versions from the readme doc into `requirements.txt`, so it's hard for me to guess how to fix.

I can update the readme doc to use both `subdirectory=...` and `egg=...`, but it's hard to know if this will help. I'll do that and then close this -- you can reopen or email me if it's still a problem.
```
pip install 'git+https://github.com/globus/globus-cwlogger@1.0#subdirectory=client&egg=globus_cw_client'
```

There are two major ways of this failing which I've bumped into. If you were playing with options for this, you might also have come across these:
```shell
# fails because it's trying to do an editable install from a non-git source
# note that this is using the tar.gz archive version
pip install -e 'https://github.com/globus/globus-cwlogger/archive/1.0.tar.gz#subdirectory=client'
# fails because two "#" chars are used, instead of "#" and "&"
pip install https://github.com/globus/globus-cwlogger@1.0#subdirectory=client#egg=globus_cw_client
```
